### PR TITLE
feat: add image component

### PR DESCRIPTION
**Pull request by mariyasada**
adding image component to CL. do review it

### CODE REVIEW

**Review by JantuDeb — APPROVED** [review]
These css for images are clean, you can merge.

**Review by tushartiwari7 — APPROVED** [review]
Code Structuring looks clean and manageable
You can merge this.

**Review by sks-21 — APPROVED** [review]
The code looks nice. Good to merge.

**Comment by t007rushi** [comment]
images are well responsive on all devices,merge it

**Pull request merged**
